kel/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as authviews
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('',include('user.urls')),
    path(
        'password-reset/',
        authviews.PasswordResetView.as_view(
            template_name = 'user/password_reset.html'
        ),
        name = 'password_reset'
    ),
    path(
        'password-reset-done/',
        authviews.PasswordResetDoneView.as_view(
            template_name = 'user/password_reset_done.html'
        ),
        name = 'password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        authviews.PasswordResetConfirmView.as_view(
            template_name = 'user/password_reset_confirm.html'
        ),
        name = 'password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        authviews.PasswordResetCompleteView.as_view(
            template_name = 'user/password_reset_complete.html'
        ),
        name = 'password_reset_complete'
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path
from . import views as landing_views

app_name = 'landing'
urlpatterns = [
    path('',landing_views.ProductListView.as_view(),name = 'home'),
    path('product/<int:pk>/',landing_views.ProductDetailView.as_view(),name = 'detail'),
    path('cart/',landing_views.CartListView.as_view(),name = 'cart'),
    path('add-to-cart/',landing_views.AddItemsToCartView.as_view(),name = 'add_to_cart'),
    path('quantity/change/',landing_views.IncreaseOrDecreaseQuantityView.as_view(),name = 'quantity_change'),
    path('item/delete/',landing_views.DeleteItemFromCartView.as_view(),name = 'delete_item'),
    path('search/',landing_views.ItemsSearchView.as_view(),name = 'search'),
]

user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from . import views as user_views


app_name = 'user'
urlpatterns = [
    path('register/signin/',LoginView.as_view(template_name = 'user/signin.html'),name = 'signin'),
    path('register/signup/',user_views.NewUserView.as_view(template_name = 'user/signup.html'),name = 'signup'),
    path('logout/',LogoutView.as_view(),name = 'logout'),
    path('user/profile/',user_views.UserProfileView.as_view(),name = "profile"),
    path('user/profile/edit/',user_views.UserEditProfileView.as_view(),name = "edit_profile"),
]

landing/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
class Product(models.Model):
    """ This is the table for the products """
    product_name = models.CharField(max_length = 100)
    product_price = models.DecimalField(decimal_places = 2,max_digits = 1000,null = False)
    product_img = models.ImageField(default = 'default.png', upload_to = 'products_images')
    product_description = models.TextField(null = False,default = "This is the products description.")
    
    def save(self):
        super().save()
        
        img = Image.open(self.product_img.path)
        
        if img.width > 300 or img.height > 250:
            output_size = (300,250)
            img.thumbnail(output_size)
            img.save(self.product_img.path)
    
    def __str__(self):
        return self.product_name
    
class UserCartItems(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    item_name = models.CharField(max_length = 100)
    item_quantity = models.IntegerField(default = 1) 
    
    def __str__(self):
        return f"{self.user.username}-> {self.item_name}"

user/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Location(models.Model):
    client = models.OneToOneField(User,on_delete = models.CASCADE,null = False,default = None)
    hall_or_hostel = models.CharField(max_length = 200)
    room_number = models.CharField(max_length=50)
    mobile_number = models.CharField(max_length = 10)
    
    def __str__(self):
        return f"{self.client.username}'s Location"
    

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Location

class NewUser(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1']
        widgets = {
            'username': forms.TextInput(attrs = {
                'class':'form-control',
                'placeholder':'Username',
            }),
            'email': forms.TextInput(attrs = {
                'class':'form-control',
                'type': 'email',
                'placeholder':'Email',
                'required':'True',
            }),
        }
        
class ClientLocation(forms.ModelForm):
    class Meta:
        model = Location
        fields = ['hall_or_hostel','room_number','mobile_number']
        widgets = {
            'hall_or_hostel': forms.TextInput(attrs ={
                'class':'form-control',
                'placeholder':'Hall or Hostel',
                
            }),
            'room_number': forms.TextInput(attrs ={
                'class':'form-control',
                'placeholder':'Room Number',
            }),
            'mobile_number': forms.TextInput(attrs ={
                'class':'form-control',
                'type':'tel',
                'placeholder':'Mobile Number',
                'maxlenght':'10',
            }),
            
        }
        help_texts = {
            'mobile_number':"Please provide the school's vodafone number if possible.",
        }
        
class UserEditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','username','email']
        widgets = {
            'first_name': forms.TextInput(attrs = {
                'class': 'form-control',
            }),
            'last_name': forms.TextInput(attrs = {
                'class': 'form-control',
            }),
            'username': forms.TextInput(attrs = {
                'class': 'form-control',
            }),
            'email': forms.TextInput(attrs = {
                'required': 'true',
                'class': 'form-control',
                'type':'email',
            }),
        }

user/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.views import View
from django.http import HttpResponseRedirect
from .models import Location
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import NewUser,ClientLocation,UserEditProfileForm

# Create your views here.

class NewUserView(View):
    template_name = 'user/signup.html'
    form_class = NewUser
    form_class2 = ClientLocation
    
    def get(self,request,*args,**kwargs):
        form = self.form_class()
        loc = self.form_class2()
        context = {
            'form':form,
            'loc':loc,
        }
        return render(request,self.template_name,context)
    
    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        loc = self.form_class2(request.POST)
        context = {
            'form':form,
            'loc':loc,
        }
        if form.is_valid():
            user = form.save()
            print(user)
            if loc.is_valid():
                location = Location(client = user,**loc.cleaned_data)
                location.save()
            messages.success(request,f'You have been successfully registered, you can now sign in.')
            return HttpResponseRedirect(reverse('user:signin'))
        return render(request,self.template_name,context)

    
class UserProfileView(View):
    """ This class displays the profile of the user """
    template_name = 'user/user_profile.html'
    
    @method_decorator(login_required)
    def dispatch(self,request,*args,**kwargs):
        return render(request,self.template_name)
    
class UserEditProfileView(LoginRequiredMixin,View):
    form_class1 = UserEditProfileForm
    form_class2 = ClientLocation
    template_name = 'user/edit_user_profile.html'
    
    def get(self,request,*args,**kwargs):
        form = self.form_class1(instance = request.user)
        loc = self.form_class2(instance = request.user.location)
        context = {
            "form":form,
            "loc":loc,
        }
        
        return render(request,self.template_name,context)
    
    def post(self,request,*args,**kwargs):
        form = self.form_class1(request.POST,instance = request.user)
        loc = self.form_class2(request.POST,instance = request.user.location)
        context = {
            "form":form,
            "loc":loc,
        }
        if form.is_valid() and loc.is_valid():
            form.save()
            loc.save()
            
            return HttpResponseRedirect(reverse('user:profile'))
        
        return render(request,self.template_name,context)
    

user/templates/user/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="{% static 'landing\bootstrap.min.css' %}"/>
    {% block head %}
    {% endblock %}
    <style>
        .card{
            box-shadow: 0px 2px 5px rgba(0,0,0,0.5);
        }
    </style>
</head>
<body>
  <div class="container">
       {% block content %}
       {% endblock %}
   </div>
    <script src="{% static 'landing\jquery-3.4.1.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

user/templates/user/edit_user_profile.html
{% extends 'user/base.html' %}


{% block head %}
    <title>Edit Profile</title>
{% endblock %}
{% block content %}
    <div class="card" style="max-width: 450px; margin:30px auto auto auto">
        <div class="card-header text-center" style="background: gold;">Edit Profile</div>
        <div class="card-body">
            <form action="." method="post">
               {% csrf_token %}
               <div class="form-group">
                    {{form.first_name}}
                </div>
                <div class="form-group">
                    {{form.last_name}}
                </div>
                <div class="form-group">
                    {{form.username}}
                </div>
                <div class="form-group">
                    {{form.email}}
                </div>
                <div class="form-group">
                    {{loc.hall_or_hostel}}
                </div>
                <div class="form-group">
                    {{loc.room_number}}
                </div>
                <div class="form-group">
                    {{loc.mobile_number}}
                    <span class="form-text small muted">{{ loc.mobile_number.help_text }}</span>
                </div>
                <button class="btn btn-block btn-outline-dark" >Save Changes</button>
            </form>
        </div>
    </div>
{% endblock %}
{% block javascript %}
{% endblock %}

user/templates/user/password_reset.html
{% extends 'user/base.html' %}


{% block head %}
    <title>Sign In</title>
{% endblock %}
{% block content %}
    <div class="card" style="max-width: 450px;margin: 100px auto;">
        <div class="card-header text-center" style="background: gold">Request Password Reset</div>
        <div class="card-body">
            <form action="." method="post">
               {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                    {{ form.email }}
                </div>
                <button class="btn btn-outline-dark btn-block">Request Password Reset</button>
            </form>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        // Add Bootstrap classes to the input fields
        $('#id_email').attr('class','form-control');
        
    </script>
{% endblock %}

user/templates/user/password_reset_complete.html
{% extends 'user/base.html' %}


{% block head %}
    <title>Sign In</title>
{% endblock %}
{% block content %}
    <div class="card" style="max-width: 450px;margin: 100px auto;">
        <div class="card-header text-center" style="background: gold">Password Reset Complete</div>
        <div class="card-body">
           <p class="text-center text-success lead">Your password has been successfully reset, you can now sign in.</p>
            <a href="{% url 'user:signin' %}" class="btn btn-block btn-outline-dark">Go To Sign In Page</a>   
        </div>         
    </div>
{% endblock %}

user/templates/user/password_reset_confirm.html
{% extends 'user/base.html' %}


{% block head %}
    <title>Sign In</title>
{% endblock %}
{% block content %}
    <div class="card" style="max-width: 450px;margin: 100px auto;">
        <div class="card-header text-center" style="background: gold">Reset Password</div>
        <div class="card-body">
            <form action="." method="post">
               {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.new_password1.id_for_label }}">{{ form.new_password1.label }}</label>
                    {{ form.new_password1 }}
                    <span class="form-text muted small">Your new password should be at least 8 words long.</span>
                </div>
                <div class="form-group">
                    <label for="{{ form.new_password2.id_for_label }}">{{ form.new_password2.label }}</label>
                    {{ form.new_password2 }}
                    <span class="form-text muted small">Enter the same password as before, for verification.</span>
                </div>
                <button class="btn btn-outline-dark btn-block">Reset Password</button>
            </form>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        // Add Bootstrap classes to the input fields
        $('#id_new_password1').attr('class','form-control');
        $('#id_new_password2').attr('class','form-control');
        
    </script>
{% endblock %}

user/templates/user/password_reset_done.html
{% extends 'user/base.html' %}


{% block head %}
    <title>Sign In</title>
{% endblock %}
{% block content %}
    <div class="card" style="max-width: 450px;margin: 100px auto;">
        <div class="card-header text-center" style="background: gold">Request Password Reset</div>
        <div class="card-body">
            <p class="text-center text-success lead">We have sent you a verification token to your email.</p>
        </div>
    </div>
{% endblock %}

user/templates/user/signin.html
{% extends 'user/base.html' %}


{% block head %}
    <title>Sign In</title>
{% endblock %}
{% block content %}
   {% if messages %}
       {% for message in messages %}
           <p class="alert alert-success">{{message}}</p>
       {% endfor %}
   {% endif %}
    <div class="card" style="max-width: 450px;margin: 100px auto;">
        <div class="card-header text-center" style="background: gold">Sign in</div>
        <div class="card-body">
            <form action="." method="post">
               {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                    {{ form.username }}
                </div>
                <div class="form-group">
                    <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
                    {{ form.password }}
                </div>
                <a href="{% url 'password_reset' %}" style="display: block;margin: 2px auto;" class="small muted text-right">Forgot Password</a><br/>
                <button class="btn btn-outline-dark btn-block">Sign In</button>
                <p class="text-center small text-muted" style="margin: 2px auto;">Need An Account? <a href="{% url 'user:signup' %}">Sign Up</a></p>
            </form>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        // Add Bootstrap classes to the input fields
        $('#id_username').attr('class','form-control')
        $('#id_password').attr('class','form-control')
    </script>
{% endblock %}

user/templates/user/signup.html
{% extends 'user/base.html' %}


{% block head %}
    <title>Sign Up</title>
    <style>
        
        .input-group{
            border: thin solid #535353;
            border-radius: 5px;
        }
        .wrapper{
            margin: 15px auto
        }
    </style>
{% endblock %}
{% block content %}
    <div class="card" style="max-width: 450px; margin:30px auto auto auto">
        <div class="card-header text-center" style="background: gold;">Sign Up</div>
        <div class="card-body">
            <form action="" method="post">
               {% csrf_token %}
                <div class="form-group">
                    {{form.username}}
                </div>
                <div class="form-group">
                    {{form.email}}
                </div>
                <div class="form-group">
                    {{loc.hall_or_hostel}}
                </div>
                <div class="form-group">
                    {{loc.room_number}}
                </div>
                <div class="form-group">
                    {{loc.mobile_number}}
                    <span class="form-text small muted">{{ loc.mobile_number.help_text }}</span>
                </div>
                <div class="form-group">
                   <span class="form-text small muted">{{ form.password1.error_messages }}</span>
                    {{form.password1}}
                    <span class="form-text small muted">
                        Your password should be at least 8 characters long.
                    </span>
                </div>
                <div class="form-group">
                    {{form.password2}}
                    <span class="form-text small muted">{{ form.password2.help_text }}</span>

                </div>
                <button class="btn btn-block btn-outline-dark" >Create Account</button>
                <p class="text-center text-muted small" style="margin: 2px auto">Already Have An Account? <a href="{% url 'user:signin' %}">Sign In</a></p>
            </form>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        // Add bootstrap classes to the fields
        $('#id_password1').attr(
            {
                'class':'form-control',
                'placeholder':'Password',
            }
        );
        $('#id_password2').attr(
            {
                'class':'form-control',
                'placeholder':'Password Confirmation',
            }
        );
    </script>
{% endblock %}

user/templates/user/user_profile.html
{% extends 'landing/base.html' %}
{% load static %}


{% block head %}
    <title>User Profile</title>
{% endblock %}
{% block content %}
    <div class="container" style="margin-top: 80px">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'user:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'landing:cart' %}">Your Cart <span class="badge badge-dark">{{ user.usercartitems_set.count }}</span></a>
            </li>
        </ul>
        <div style="text-align: center;margin-top: 20px;">
            <!-- User Image -->
            <img src="{% static 'landing/images/user.jpg' %}" style = 'width: 200px;height: 200px;border-radius: 50%;border: 5px solid lightgray;position: relative;z-index: 1;' alt="Avatar">
            <hr style = ';max-width: 400px;position: relative;top: -100px;margin: auto;z-index: 0;border: 3px solid rgba(0,0,0,0.125);border-radius: 10px;'/>
            <div style = 'max-width: 400px;margin: 10px auto auto auto'>
                <h5 class = 'text-left'>First Name :<span class = 'text-info'>{{ user.first_name }}</span></h5>
                <h5 class = 'text-left'>Last Name :<span class = 'text-info'>{{ user.last_name }}</span></h5>
                <h5 class = 'text-left'>Username :<span class = 'text-info'>{{ user.username }}</span></h5>
                <h5 class = 'text-left'>Email :<span class = 'text-info'>{{ user.email }}</span></h5>
                <h5 class = 'text-left'>Hall/Hostel :<span class = 'text-info'>{{ user.location.hall_or_hostel }}</span></h5>
                <h5 class = 'text-left'>Room number :<span class = 'text-info'>{{ user.location.room_number }}</span></h5>
                <h5 class = 'text-left'>Mobile number :<span class = 'text-info'>{{ user.location.mobile_number }}</span></h5>
                <h5 class = 'text-left'>No of items in cart :<span class = 'text-info'>{{ user.usercartitems_set.count }}</span></h5>
                <a href="{% url 'user:edit_profile' %}" class="btn btn-block btn-outline-dark btn-sm">Edit Profile</a>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
{% endblock %}