kel/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as authviews
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('',include('user.urls')),
    path(
        'password-reset/',
        authviews.PasswordResetView.as_view(
            template_name = 'user/password_reset.html'
        ),
        name = 'password_reset'
    ),
    path(
        'password-reset-done/',
        authviews.PasswordResetDoneView.as_view(
            template_name = 'user/password_reset_done.html'
        ),
        name = 'password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        authviews.PasswordResetConfirmView.as_view(
            template_name = 'user/password_reset_confirm.html'
        ),
        name = 'password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        authviews.PasswordResetCompleteView.as_view(
            template_name = 'user/password_reset_complete.html'
        ),
        name = 'password_reset_complete'
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path
from . import views as landing_views

app_name = 'landing'
urlpatterns = [
    path('',landing_views.ProductListView.as_view(),name = 'home'),
    path('product/<int:pk>/',landing_views.ProductDetailView.as_view(),name = 'detail'),
    path('cart/',landing_views.CartListView.as_view(),name = 'cart'),
    path('add-to-cart/',landing_views.AddItemsToCartView.as_view(),name = 'add_to_cart'),
    path('quantity/change/',landing_views.IncreaseOrDecreaseQuantityView.as_view(),name = 'quantity_change'),
    path('item/delete/',landing_views.DeleteItemFromCartView.as_view(),name = 'delete_item'),
    path('search/',landing_views.ItemsSearchView.as_view(),name = 'search'),
]

user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from . import views as user_views


app_name = 'user'
urlpatterns = [
    path('register/signin/',LoginView.as_view(template_name = 'user/signin.html'),name = 'signin'),
    path('register/signup/',user_views.NewUserView.as_view(template_name = 'user/signup.html'),name = 'signup'),
    path('logout/',LogoutView.as_view(),name = 'logout'),
    path('user/profile/',user_views.UserProfileView.as_view(),name = "profile"),
    path('user/profile/edit/',user_views.UserEditProfileView.as_view(),name = "edit_profile"),
]

landing/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
class Product(models.Model):
    """ This is the table for the products """
    product_name = models.CharField(max_length = 100)
    product_price = models.DecimalField(decimal_places = 2,max_digits = 1000,null = False)
    product_img = models.ImageField(default = 'default.png', upload_to = 'products_images')
    product_description = models.TextField(null = False,default = "This is the products description.")
    
    def save(self):
        super().save()
        
        img = Image.open(self.product_img.path)
        
        if img.width > 300 or img.height > 250:
            output_size = (300,250)
            img.thumbnail(output_size)
            img.save(self.product_img.path)
    
    def __str__(self):
        return self.product_name
    
class UserCartItems(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    item_name = models.CharField(max_length = 100)
    item_quantity = models.IntegerField(default = 1) 
    
    def __str__(self):
        return f"{self.user.username}-> {self.item_name}"

landing/views.py
from django.shortcuts import render,get_object_or_404
from django.http import JsonResponse
from django.views import View,generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Product,UserCartItems


# Create your views here.

class ProductListView(generic.ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'landing/index.html'
    
    def get_context_data(self,*args,**kwargs):
        """ This method adds another key to the dictionary that will show if an item which is being displayed is already in the user's cart """
        context = super().get_context_data(*args,**kwargs)
        if self.request.user.is_authenticated:
            added_items = [pro for pro in  Product.objects.all() for item in self.request.user.usercartitems_set.all() if pro.product_name == item.item_name ]
            context['added_items'] = added_items
            
        return context
    
class ProductDetailView(generic.DetailView):
    model = Product
    
    def get_context_data(self,*args,**kwargs):
        # Get the context data
        context = super().get_context_data(*args,**kwargs)
        if self.request.user.is_authenticated:
            added_items = [pro for pro in  Product.objects.all() for item in self.request.user.usercartitems_set.all() if pro.product_name == item.item_name ]
            context['added_items'] = added_items
        # Get the product beign showed
        product_id = int(self.kwargs.get('pk'))
        other_products = Product.objects.exclude(id = product_id)
        context["other_products"] = other_products
        return context
    
class AddItemsToCartView(View):
    def get(self,request,*args,**kwargs):
        """ This method adds an item to a userscart """
        # Use the id of the product to get the product
        product_id = int(request.GET.get('product_id',None))
        product = get_object_or_404(Product,id = product_id)
        # Add product to the user's cart
        request.user.usercartitems_set.create(item_name = product.product_name)
        data = {
                'total_basket_items':request.user.usercartitems_set.count(),
        }
        
        return JsonResponse(data)

    
class ItemsSearchView(generic.ListView):
    """ This class returns the search results """
    model = Product
    template_name = 'landing/search_results.html'
    
    def get_context_data(self,*args,**kwargs):
        results = self.request.GET.get("q");
        context = super().get_context_data(*args,**kwargs)
        context['results'] = Product.objects.filter(product_name__icontains = results)
        if self.request.user.is_authenticated:
            added_items = [pro for pro in  Product.objects.all() for item in self.request.user.usercartitems_set.all() if pro.product_name == item.item_name ]
            context['added_items'] = added_items
        print(context['results'])
        return context


class CartListView(LoginRequiredMixin,generic.ListView):
    model = Product
    template_name = 'landing/cart.html'
    context_object_name = 'cart_items'
    
    def get_queryset(self,*args,**kwargs):
        queryset = [(pro,cart) for pro in Product.objects.all() for cart in self.request.user.usercartitems_set.all() if cart.item_name == pro.product_name]
        return queryset
    
    
class IncreaseOrDecreaseQuantityView(LoginRequiredMixin,View):
    """ This class either increses or decreases the quantity of an item in a userscart """
    def get(self,request,*args,**kwargs):
        # Use the id of the item  to get the item
        item_id = int(request.GET.get("item_id",None))
        item = get_object_or_404(UserCartItems,id = item_id)
        # Should we increase or decrease the quantity
        operation = request.GET.get('operation',None)
        if operation == 'add':
            item.item_quantity += 1
            item.save()
        else:
            item.item_quantity -= 1
            item.save()
        
        data = {
            'quantity': item.item_quantity,
        }
        
        return JsonResponse(data)
    
class DeleteItemFromCartView(LoginRequiredMixin,View):
    """ This class deletes an item from the users cart """
    def get(self,request,*args,**kwargs):
        # Get the item using the id
        item_id = int(request.GET.get("item_id",None))
        item = get_object_or_404(UserCartItems,id = item_id)
        # Remove it from the user's cart
        item.delete()
        
        data = {
            'cart':request.user.usercartitems_set.count(),
        }
        
        return JsonResponse(data)
    

landing/templates/landing/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="{% static 'landing\bootstrap.min.css' %}"/>
    <style>
        nav{
            background-color: royalblue;
        }
    </style>
    {% block head %}
    {% endblock %}
</head>
<body>
    <div class="container">
        <nav class="navbar fixed-top navbar-expand-md navbar-dark navbar-outline-dark">
          <a class="navbar-brand" href="{% url 'landing:home' %}"><h5>What's Your Need</h5></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
           <!-- Form Section -->
            <form action="{% url 'landing:search' %}" class="form-inline my-2 my-lg-0" style="width: calc(100% - 250px)">
              <input class="form-control mr-sm-2 mr-2" type="search" placeholder="Search for goods.." name="q" style="width: calc(100% - 90px)">
              <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
            </form>
            <!-- User Section -->
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
               <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <img src="{% static 'landing\images\man-user.png' %}"/>
                      {% if user.is_authenticated %}
                        Hi {{ user.username }}
                      {% endif %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                     {% if user.is_authenticated %}
                          <a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>
                      {% else %}
                          <a class="dropdown-item" href="{% url 'user:signin' %}">Login</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{% url 'user:signup' %}">Register</a>
                      {% endif %}
                    </div>
                </li>
                <!-- Basket Section -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'landing:cart' %}" style = "position: relative">
                       <span style="position: absolute;left: 18px;top: 2px;" class="badge badge-light" id="basket-items">
                           {% if user.is_authenticated %}
                               {{user.usercartitems_set.count}}
                           {% else %}
                                0
                           {% endif %}
                       </span>
                        <img src="{% static 'landing\images\shopping-cart.png' %}" alt="">
                    </a>
                  </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    <script src="{% static 'landing\jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'landing\bootstrap.min.js' %}"></script>
    <script>
        let form = $('form');
        let searchBar = $('input[type = "search"]');
        let navBar = $('nav');
        // Changes the width of the form and input field when it reaches a certain level
        if( window.innerWidth < 767 ){
                form.css('width','auto');
            }
            else{
                form.css('width','calc(100% - 100px)');
            }
        
        window.onresize = () => {
            if( window.innerWidth < 767 ){
                form.css('width','auto');
            }
            else{
                form.css('width','calc(100% - 100px)');
            }
//            console.log(window.innerWidth)
        }
        
        // Create a function that adds a product to the user's cart
        let addProductTocart = () => {
            $('.add-product').click(function(){
                if($(this).text() !== "Added"){
                    let productId = $(this).attr('id');
                    $.ajax({
                        url: "{% url 'landing:add_to_cart' %}",
                        data: {
                            "product_id": productId,
                        },
                        dataType: "json",
                        success: function(data){
                            $('#basket-items').text(data['total_basket_items']);
                        }
                    })
                    $(this).text("Added");
                    $(this).attr("class","btn btn-primary btn-block btn-sm disabled");
                }
            })
        }
        addProductTocart(); // Invoke
    </script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

landing/templates/landing/cart.html
{% extends 'landing/base.html' %}
{% load static %}

{% block head %}
    <title>Cart</title>
    <style>
        body{
            user-select: none;
        }
        p{
            margin: auto;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid" id="wrapper" style="margin-top: 80px;">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'landing:cart' %}">Your Cart <span class = 'badge badge-dark' id="profile-basket-items">{{ user.usercartitems_set.count }}</span></a>
            </li>
        </ul>
        {% if cart_items %}
            <div style="margin-top: 20px;" id="row-container" class="row row-cols-lg-3 row-cols-md-2 row-cols-sm-2 row-cols-1">
                {% for item,qua in cart_items %}
                    <div class="col">
                       <!-- Cart Item Section -->
                        <div class="card mt-3" style="border-top: medium solid royalblue;box-shadow: 0px 2px 5px rgba(0,0,0,.3)">
                            <div class="row row-cols-2 no-gutters">
                                <!-- Cart Item Image -->
                                <div class="col" style="border-right: thin solid lightgray">
                                    <img style="width: 100%;height: 100%;" src="{{ item.product_img.url }}" alt="{{ item.product_name }} Image">
                                </div>
                                <!-- Cart Options -->
                                <div class="col cart-options-container" style="padding: 3px;">
                                   <!-- Product Name -->
                                    <p class="lead">{{ item.product_name }}</p>
                                    <!-- Product Price -->
                                    <p style = 'font-size:14px;' class="small text-info">
                                        Price: <span style="font-size: 14px;" class="text-dark price">GH&#8373;{{ item.product_price }}</span>
                                    </p>
                                    <!-- Quantity -->
                                    <p style = 'font-size:14px;' id="{{ qua.id }}" class="small text-info">
                                        Quantity:
                                        <span style = 'font-size:14px;cursor:pointer;' style = 'font-size:14px;' title="Increase" class="badge badge-dark add">+</span>
                                        <span style="font-size: 14px;" class="text-dark quantity">{{ qua.item_quantity }}</span>
                                        <span style = 'font-size:14px;cursor:pointer;'  class="badge badge-dark sub" title="Decrease">-</span>
                                    </p>
                                    <!-- Sub Total -->
                                    <p style = 'font-size:14px;' class="small text-info">
                                        Sub-Total: <span style="font-size: 14px;" class="text-dark subtotal">GH&#8373;{{ item.product_price }}</span>
                                    </p>
                                    <button class="btn btn-danger btn-sm btn-block mt-3 delete" id="{{ qua.id }}">
                                        <img style="width: 16px;height: 16px;position: relative;top: -2px;" src="{% static 'landing/images/delete.png' %}" alt="Delete Item"> Remove
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="mt-3" id="total-container" style="max-width: 600px;margin: auto;">
                <h4 style = 'color: #0069d9;display:inline-block;padding:.375rem .75rem;border:thin solid #0069d9;border-radius:5px;font-size:20px;position:relative;top:5px;width:calc(100%/2.1);text-align:center'>Total: GH&#8373;<span id="total"></span></h4>
                <a href="" class="btn btn-primary" style="width:calc(100%/2.1);">Place an order</a>
            </div>
        {% else %}
            <div style="max-width: 600px;margin: auto">
               <h1 class="text-center mt-5">Sorry you have no items in your cart..</h1>
               <a href="{% url 'landing:home' %}" class="btn btn-info btn-block mt-5">Continue Shopping..</a> 
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block javascript %}
    <script>
        // A function that calculates the subtotal
        let calculateSubtotal = (number,element) => {
            // Get the quantity, price and subtotal
            let quantity = Number($(element).eq(number).find('.quantity').text().trim());
            let price = Number($(element).eq(number).find('.price').text().slice(3,).trim());
            let subtotal = $(element).eq(number).find('.subtotal');
            let product = quantity * price;
            let product_list = String(product).split('.');
            // Make some modifications to the data
            if(product_list.length == 1){
                product_list.push('00'); 
            }
            else{
                if(product_list[1].length > 2){
                    product_list[1] = product_list[1].slice(0,2);
                }
                else if(product_list[1].length == 1){
                    product_list[1] = product_list[1].padEnd(2,'0');
                }
            }
            // Change the subtotal
            subtotal.text(`GHC${product_list.join('.')}`);
        }
        // Add the fuction to an event
        $(".cart-options-container").each(function(number,element){
            calculateSubtotal(number,`.${element.classList["1"]}`);
        })
        
        // A function that calculates the total
        let calculateTotal = () => {
            let total = 0;
            let total_element = $('#total');
            $('.subtotal').each(function(){
                total += Number($(this).text().slice(3,));
            })
            let total_list = String(total).split('.');
            if(total_list.length < 2){
                total_list.push('00');
            }
            else{
                if(total_list[1].length == 1){
                    total_list[1] = total_list[1].padEnd(2,'0');
                }
                else if(total_list[1].length > 2){
                    total_list[1] = total_list[1].slice(0,2);
                }
            }
            
            total_element.text(total_list.join('.'));
            
        }
        calculateTotal() // Invoke the function
        
        // A function that increases or decreses the quantity of an item
        let increaseOrDecreaseQuantity = () => {
            
            //  A function that makes an ajax request to either increase or decreased the quantity
            let ajaxRequestQuantityChange = (item_id,quantity,operation,number,element) => {
                $.ajax({
                    url: "{% url 'landing:quantity_change' %}",
                    data: {
                        'item_id': item_id,
                        'operation': operation,
                    },
                    dataType: 'json',
                    success: function(data){
                        quantity.text(data['quantity']);
                        // Calculate the subtotal for element which had his quantity changed
                        calculateSubtotal(number,element);
                        // Calculate the total of all the goods in the user's cart
                        calculateTotal();
                    },
                })
            }            
            
            // Increase quantity
            $('.add').click(function(){
                let parent = $(this).parent();
                let item_id = parent.attr('id');
                let item_quantity = parent.find('.quantity');
                let index = Number($('.add').index(this));
                let element = parent.parent().attr('class').split(' ')[1];
                if(Number(item_quantity.text()) + 1 < 100){
                    ajaxRequestQuantityChange(item_id,item_quantity,'add',index,`.${element}`);
                }
            })
            // Decrease quantity
            $('.sub').click(function(){
                let parent = $(this).parent();
                let item_id = parent.attr('id');
                let item_quantity = parent.find('.quantity');
                let index = Number($('.sub').index(this));
                let element = parent.parent().attr('class').split(' ')[1];
                if(Number(item_quantity.text()) - 1 > 0){
                    ajaxRequestQuantityChange(item_id,item_quantity,'sub',index,`.${element}`);
                }

            })
        }
        increaseOrDecreaseQuantity() // Invoke the function
        
        // A function that will removes an item from the user's cart
        let removeItemFromCart = () => {
            $('.delete').click(function(){
                let item_id = $(this).attr('id');
                let parent = $(this).parent().parent().parent().parent()
                $.ajax({
                    url: "{% url 'landing:delete_item' %}",
                    data: {
                        'item_id':item_id,
                    },
                    dataType: 'json',
                    success: function(data){
                        // Modify the number of items in the cart
                        $('#basket-items').text(data['cart']);
                        $('#profile-basket-items').text(data['cart']);
                        // Remove the item in the frontend
                        parent.hide(function(){
                            $(this).remove();
                            if(data['cart'] == 0){
                                    $('#row-container').remove();
                                    $('#total-container').hide(function(){
                                        $(this).remove();
                                        $('#wrapper').append(
                                            `<div style="max-width: 600px;margin: auto">
                                               <h1 class="text-center mt-5">Sorry you have no items in your cart..</h1>
                                               <a href="{% url 'landing:home' %}" class="btn btn-info btn-block mt-5">Continue Shopping..</a> 
                                            </div>`
                                        );
                                    }
                                                               )
                               }
                            // Calculate the total of all the goods in the user's cart
                            calculateTotal()
                        })
                        
                    },
                })
            })
        }
        removeItemFromCart() // Invoke the function
    </script>
{% endblock %}

landing/templates/landing/index.html
{% extends 'landing/base.html' %}


{% block head %}
    <title>Home</title>
    <style>
        a{
            display: block;
            color: #535353;
        }
        a:hover{
            text-decoration: none;
            color: royalblue;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container" style="margin-top: 80px;">
        <div class="row row-cols-lg-5 row-cols-md-4 row-cols-sm-3 row-cols-2" >
            {% for good in products %}
                <div class="col">
                    <div class="card" style="box-shadow: 0px 2px 5px rgba(0,0,0,0.5);">
                        <img src="{{ good.product_img.url }}" class="card-img-top" alt="{{ goood.product_name }}">
                        <hr style = 'margin: auto; width: 100%;'/>
                        <div style="padding: 8px 5px;">
                           <a href="{% url 'landing:detail' good.pk %}" class = "lead text-center" style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;" >{{ good.product_name }}</a>
                            <span style="font-size: 14px;">GH&#8373; {{ good.product_price }}</span>
                            {% if user.is_authenticated and good in added_items %}
                                <button class="btn btn-primary btn-block btn-sm disabled">Added</button>
                            {% elif user.is_authenticated %}
                                <button id="{{ good.id }}" class="btn btn-primary btn-block btn-sm add-product">Add to basket</button>
                            {% else %}
                                <a href="{% url 'user:signin' %}" class="btn btn-primary btn-block btn-sm">Add to basket</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block javascript %}
    
{% endblock %}

landing/templates/landing/search_results.html
{% extends 'landing/base.html' %}


{% block head%}
    <title>Search Results</title>
    <style>
        a{
            display: block;
            color: #535353;
        }
        a:hover{
            text-decoration: none;
            color: royalblue;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container" style="margin-top: 80px">
       {% if results %}
            <div class="row row-cols-lg-5 row-cols-md-4 row-cols-sm-3 row-cols-2" >
                {% for good in results %}
                    <div class="col">
                        <div class="card" style="box-shadow: 0px 2px 5px rgba(0,0,0,0.5);">
                            <img src="{{ good.product_img.url }}" class="card-img-top" alt="{{ goood.product_name }}">
                            <hr style = 'margin: auto; width: 100%;'/>
                            <div style="padding: 8px 5px;">
                               <a href="{% url 'landing:detail' good.pk %}" class = "lead text-center" style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;" >{{ good.product_name }}</a>
                                <span style="font-size: 14px;">GH&#8373; {{ good.product_price }}</span>
                                {% if user.is_authenticated and good in added_items %}
                                    <button class="btn btn-primary btn-block btn-sm disabled">Added</button>
                                {% elif user.is_authenticated %}
                                    <button id="{{ good.id }}" class="btn btn-primary btn-block btn-sm add-product">Add to basket</button>
                                {% else %}
                                    <a href="{% url 'user:signin' %}" class="btn btn-primary btn-block btn-sm">Add to basket</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div style="margin: 20px auto;max-width: 600px; padding: 5px;">
                <h1 class="text-center">No results found...</h1>
                <a href="{% url 'landing:home' %}" class="btn btn-block btn-primary">Continue Shopping</a>
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block javascript %}
    <script>
    </script>
{% endblock %}